### ISSUE TITLE
Multi-variable capabilities?

### ISSUE THREAD

**Issue by rafizulfahmi** [MrcJkb/tcpip4diac#1]
Hello Mr. Jacobi. It's have been awhile since i contacting you in Linkedin

I've got a question with this tcp4diac library. I've found out that the number of variables that i need to communicate back-and-forth between MATLAB and 4DIAC is exceeding max port that's available with 4DIAC's standard server/client function. I've been trying to create custom function blocks since that could handle the numbers. 

The questions is, if i suceeded in creating one, could the tcpip4diac matlab item handles variables with more than max port that available with standard 4DIAC's server/client function block? (say 20 variables)

Thankyou

**Comment by mrcjkb** [comment]
Hi Rafi,

In both 4diac-RTE (FORTE) and the tcpip4diac Matlab library, the number of inputs and outputs of a client or server can be extended to an arbitrary number.

To do so in 4diac, just copy one of the existing function blocks and edit the interface. Add the inputs/outputs you need. Make sure the function block is named according to the number of inputs and outputs (e.g., CLIENT_1_20 for a client function block with 1 data input and 20 data outputs). There is no need to deploy the function block to FORTE.

In Matlab, you have to declare the appropriate "DataInputs" and "DataOutputs" options, but it should definitely be able to handle an arbitrary number of inputs and outputs, just like the 4diac function blocks.

If you have a large number of variables of the same data type, you might also want to consider sending them in arrays. That may make the interface a bit cleaner.

Yours sincerely,
Marc

**Comment by rafizulfahmi** [comment]
Thankyou for the solution, Mr. Jakobi.
I'm currently working on the blocks as your solution goes, i'll update it when it done.

Meanwhile, i got another problem. The variables that i'm trying to pass from 4diac are need to be passed on to simulink in real time. Currently, the solutions that i can concur is that i need to initiate the tcpip object inside the callback function to enable the real time-ness while sending the data from 4diac. The data will be updated to a simulink block through get_param/set_param function. Is it possible now to use it inside callback function of a block?

Thankyou

**Comment by mrcjkb** [comment]
Sorry for the late reply. For some reason, the e-mail notification ended up in my junk folder.

I haven't used the library with Simulink yet, but I don't think you can use it directly within a callback. However, it might be possible if you wrap a persistent tcpip4diac object in a function that is executed by the callback (or a Matlab function block).

[Here is a thread in which someone used a Matlab function block to create a TCP/IP server.](https://www.mathworks.com/matlabcentral/answers/345216-tcpip-simulink-block-as-server)
Maybe something similar can be achieved with the tcpip4diac library.

**Comment by rafizulfahmi** [comment]
Thankyou Mr. Jakobi.  I've gone offline for some days due to some affairs in places with bad internet connection, so i've just been able to replying to your thread.

I've been able to applying your solutions as inspiration though. In my case, i wrapped it in a level-2 s function block. The level-2 s function's structure enabled it to send the data directly without acessing the workspace during simulation, so it can be done in real time

Here are the files, thought it would be useful for future use
[S Function.zip](https://github.com/MrcJkb/tcpip4diac/files/2210126/S.Function.zip)

I use the 'client in MATLAB - server in FORTE' methods. The models are a simple back-and-forth sending constants between 4diac and matlab. I've included a simple real-time-pacer blocks for simulink from File Exchange. The model was created in MATLAB 2016a.

**Comment by mrcjkb** [comment]
Hi Rafi,
Glad to hear you found a solution. And thanks for adding the files here. Would you like to/have time to push them to my repository (along with a license - make sure to add credit to the author of the real-time-pacer blocks)? I could see many people finding a good use for your Simulink block :)
