### ISSUE TITLE
Own SIFB cannot communicate with tcpip@4diac?

### ISSUE THREAD

**Issue by Anon-adam** [MrcJkb/tcpip4diac#2]
Hello Mr. Jacobi, 
i created my own SIFB, compiled with FORTE, and i found that the SIFB failed to communicate with the developed FB network. i can send a var or str to SIFB, and input and output data can watch the var/str, but RSP and IND didnot change the value, and therefore the following basic FB cannot work, finally, i cannot get the feedback in MATLAB. however, i copied the SIFB from the folder of net, and it works. I need to communicate with my own basic and composite FBs, your suggestions are much appreciated.
Thank you in advance.

**Comment by mrcjkb** [comment]
Hi,
if I understand correctly, you have created your own CLIENT/SERVER SIFBs and they do not work correctly.
When creating a custom CLIENT/SERVER SIFB based on an existing one in the 4diac function block library (with a custom number of inputs/outputs), you do not have to compile Forte. They should work out of the box, if I remember correctly. The only SIFBs you need to compile with Forte are "external event SIFBs" (https://www.eclipse.org/4diac/en_help.php?helppage=html/development/externalEvent_example.html).

I have some examples in my PVTControllerLib project: https://github.com/MrcJkb/PVTControllerLib/tree/master/Utils (last tested with 4diac 1.9 on Linux).
If you are having trouble on the 4diac side, I suggest you contact their support: https://www.eclipse.org/4diac/en_com.php

**Comment by SichaoLiuKTH** [comment]
> Hi,
> if I understand correctly, you have created your own CLIENT/SERVER SIFBs and they do not work correctly.
> When creating a custom CLIENT/SERVER SIFB based on an existing one in the 4diac function block library (with a custom number of inputs/outputs), you do not have to compile Forte. They should work out of the box, if I remember correctly. The only SIFBs you need to compile with Forte are "external event SIFBs" (https://www.eclipse.org/4diac/en_help.php?helppage=html/development/externalEvent_example.html).
> 
> I have some examples in my PVTControllerLib project: https://github.com/MrcJkb/PVTControllerLib/tree/master/Utils (last tested with 4diac 1.9 on Linux).
> If you are having trouble on the 4diac side, I suggest you contact their support: https://www.eclipse.org/4diac/en_com.php

**Comment by Anon-adam** [comment]
Hello Mr. Jacobi,
Thank you for your nice reply, and I created FB from the library. I have another question, and how can the function block be saved as an image from 4diac ide? Thank you in advance.

**Comment by mrcjkb** [comment]
It looks like printing features have been dropped in 4diac 1.9. 
https://www.eclipse.org/forums/index.php/t/1093942/

Please refer to the 4diac forum for questions that do not relate to my projects.
